# logs
log_format main '[$time_local] [ORIGIN: $remote_addr:$remote_port] [HOST: $host] [REQUEST: $request] [CODE: $status] [SIZE: $body_bytes_sent bytes] "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
access_log /dev/stdout main;
access_log /var/log/nginx/access.log main;

# performance
sendfile on;
keepalive_timeout 65;
gzip on;

# SSL optimization
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 20m;