
server {
	# Please don't remove this line, it helps to apply the 
	# necessary SSL configurations for each running mode 
	# The name of the file needs
	# to be the same defined on conf.json
	include /etc/nginx/conf/someid.conf;
	
	server_name example.com;

	location / {
		proxy_pass http://service1:12345/;
	}
}
